global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:

  - job_name: 'nodeexporter'
    scrape_interval: 15s
    scrape_timeout:  3s
    file_sd_configs:
      - files:
        - targets/nodeexporter.json

  - job_name: 'prometheus'
    scrape_interval: 20s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'telegraf'
    scrape_interval: 30s
    static_configs:
      - targets: ['telegraf:9126']

# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets: 
#       - 'alertmanager:9093'

# rule_files:
#   - "rules/pre_prod.yml"
