- name: Deploy TeachUA Backend
  hosts: backend
  become: true
  vars:
    db_port: 5432
    db_user: pmp2025
    dump_file: teachua_full_dump.sql
    packages:
      - postgresql-client
      - python3-psycopg2
    params:
      vault_url: "https://roma-kv-dev3.vault.azure.net/"
      client_id: "{{ azure_client_id }}"
      secret: "{{ azure_client_secret }}"
      tenant: "{{ azure_tenant_id }}"
    
  pre_tasks:
    - name: Debug params
      debug:
        var: params
        
    - name: Load secrets from Azure Key Vault
      set_fact:
        postgres_admin_user: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'pgadmin', params) }}"
        postgres_admin_password: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'pg-pass', params) }}"
        db_name: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-name', params) }}"
        db_password: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-password', params) }}"
        db_host: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-host', params) }}"
  roles:
    - role: backend
      vars:
        db_host: "{{ db_host }}"
        db_port: "{{ db_port }}"
        postgres_admin_user: "{{ postgres_admin_user }}"
        postgres_admin_password: "{{ postgres_admin_password }}"
        db_name: "{{ db_name }}"
        db_user: "{{ db_user }}"
        db_password: "{{ db_password }}"
