- name: Deploy TeachUA Backend
  hosts: backend
  become: true
  vars:
    db_user: "{{ db_user }}"
    db_password: "{{ db_password }}"
    postgres_admin_user: "{{ postgres_admin_user }}"
    postgres_admin_password: "{{ postgres_admin_password }}"
    db_host: "{{ db_host }}"
    db_port: 5432
    dump_file: teachua_full_dump.sql
    packages:
      - postgresql-client
      - python3-psycopg2
  roles:
    - role: backend
      vars:
        db_user: "{{ db_user }}"
        db_password: "{{ db_password }}"
        postgres_admin_user: "{{ postgres_admin_user }}"
        postgres_admin_password: "{{ postgres_admin_password }}"
        db_host: "{{ db_host }}"
        db_port: "{{ db_port }}"
