- name: Retrieve secrets from Azure Key Vault (locally)
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Load secrets from Azure Key Vault
      set_fact:
        secret_values:
          postgres_admin_user: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'pgadmin', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"
          postgres_admin_password: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'pg-pass', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"
          db_name: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-name', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"
          db_password: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-password', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"
          db_host: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-host', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"
      register: secrets_fact

- name: Deploy TeachUA Backend
  hosts: backend
  become: true
  vars:
    postgres_admin_user: "{{ hostvars['localhost']['secret_values']['postgres_admin_user'] }}"
    postgres_admin_password: "{{ hostvars['localhost']['secret_values']['postgres_admin_password'] }}"
    db_name: "{{ hostvars['localhost']['secret_values']['db_name'] }}"
    db_password: "{{ hostvars['localhost']['secret_values']['db_password'] }}"
    db_host: "{{ hostvars['localhost']['secret_values']['db_host'] }}"
    db_port: 5432
    db_user: pmp2025
    dump_file: teachua_full_dump.sql
  roles:
    - role: backend
