- name: Deploy TeachUA Backend
  hosts: backend
  become: true
  vars:
    db_port: 5432
    db_user: pmp2025
    dump_file: teachua_full_dump.sql
    packages:
      - postgresql-client
      - python3-psycopg2
  roles:
    - role: backend
