- name: Deploy TeachUA Backend
  hosts: backend
  become: true
  pre_tasks:
    - name: Load secrets from Azure Key Vault
      set_fact:
        postgres_admin_user: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'pgadmin', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"
        postgres_admin_password: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'pg-pass', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"
        db_name: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-name', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"
        db_password: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-password', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"
        db_host: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-host', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='environment') }}"

  vars:
    db_port: 5432
    db_user: pmp2025
    dump_file: teachua_full_dump.sql
    packages:
      - postgresql-client
      - python3-psycopg2

  roles:
    - role: backend
      vars:
        postgres_host: "{{ db_host }}"
        postgres_port: "{{ db_port }}"
        postgres_admin_user: "{{ postgres_admin_user }}"
        postgres_admin_password: "{{ postgres_admin_password }}"
        app_db_name: "{{ db_name }}"
        app_db_user: "{{ db_user }}"
        app_db_password: "{{ db_password }}"
