- name: Deploy TeachUA Frontend
  hosts: frontend
  become: true

  vars:
    # override these if needed
    docker_image: "rodriguez2711/frontend-teachua"
    docker_image_tag: "latest"
    container_name: "frontend-teachua"
    network_name: "teachua_net"
    backend_host: "{{ backend_ip }}"
    backend_port: 8080

  roles:
    - frontend
