- hosts: postgres_flexible
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Load secrets from Azure Key Vault
      set_fact:
        postgres_admin_user: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'pgadmin', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='cli') }}"
        postgres_admin_password: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'pg-pass', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='cli') }}"
        db_name: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-name', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='cli') }}"
        db_password: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'db-password', vault_url='https://roma-kv-dev3.vault.azure.net', auth_source='cli') }}"

  vars:
    db_host: roma-postgres-server-dev182.postgres.database.azure.com
    db_port: 5432
    db_user: pmp2025
    dump_file: teachua_full_dump.sql
    packages:
      - postgresql-client
      - python3-psycopg2

  roles:
    - postgresql

