---
- name: Play installing prometheus
  hosts: monitoring
  gather_facts: true
  become: true
  roles:
    - "prometheus"
  vars:
      node_ips:
        - "{{ backend_pr_ip }}:9100"
        - "{{ frontend_pr_ip }}:9100"

      api_hosts:
      - "http://{{ backend_ip }}:8080"
      - "http://{{ frontend_ip }}:80"
      
      app_db_user: "{{ db_user }}"
      app_db_password: "{{ db_password }}"
      pg_db: "teachua"
