services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - /var/prometheus/data:/var/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/var/prometheus/data'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      # - '--log.level=debug'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    - ./telegraf/telegraf.d:/etc/telegraf/telegraf.d
    ports:
      - "9126:9126"
    networks:
      -  monitor-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"


  grafana:
    image: grafana/grafana:latest
    container_name: mon_grafana   
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/plugins:/data/grafana/plugins
      # - ./grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
    restart: unless-stopped
    ports:
      - "3000:3000"
    user: "0"
    # environment:
    # - "GF_INSTALL_PLUGINS=grafana-worldmap-panel,grafana-piechart-panel,ryantxu-ajax-panel,briangann-gauge-panel,agenty-flowcharting-panel,grafana-clock-panel"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

#   nginx:
#     container_name: monitor-nginx
#     image: nginx:alpine
#     environment:
#        - TZ=America/New_York
#     volumes:
#       - ./nginx/ssl/:/etc/nginx/ssl/
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - "443:443"
#     restart: unless-stopped
#     networks:
#       - monitor-net

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)' # ask about
    restart: unless-stopped
    ports:
      - 9100:9100
    networks:
      - monitor-net
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

networks:
  monitor-net:
    driver: bridge

